---
- hosts: network_switches

  tasks:
    - name: Ensure VLAN 2 exists with the name test-vlan-2 and is in the operational state
      nxos_vlan:
        vlan_id: 2
        admin_state: up
        name: test-vlan-2
    - name: run show version on remote devices
      nxos_command:
        commands: copy run start
