---
- hosts: network_switches
gather_facts: no

  tasks:
    - name: Ensure VLAN 50 exists with the name WEB and is in the shutdown state
      nxos_vlan:
        vlan_id: 2
        admin_state: up
        name: test-vlan-2
