---
- name: Create file on server
  hosts: windows
  tasks:
    - name: Create directory 
      win_file: 
        path: c:\temp\
        state: "directory"
    - name: Create file 
      win_file: 
        path: c:\temp\demo.txt
        state: "touch"
