---
- hosts: localhost
  - name: create the VM
    ec2:
    key_name: default
    instance_type: t2.micro
    image: ami-087c2c50437d0b80d
    wait: yes
    group: webserver
    count: 3
    assign_public_ip: yes
