---
- hosts: localhost
  gather_facts: False

  tasks:

    - name: Provision an instance
      ec2:
         key_name: SDXic-mgmt
         group: default
         instance_type: t2.micro
         image: ami-0520e698dd500b1d1
         region: us-east-2
         wait: yes
         exact_count: 1
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
      register: ec2

   - name: Add all instance public IPs to host group
     add_host: hostname={{ item.public_ip }} groups=ec2hosts
     loop: "{{ ec2.instances }}
