- name: test simple powershell module - get OS version and test for minimum desired version
  hosts: windows
  tasks:
    - name: simple powershell module example to get Windows OS version
      get_version:
        major: "5"
        minor: "1"
        build: "14393"
