- name: test simple powershell module - get OS version and test for minimum desired version
  hosts: windows
  tasks:
    - enable_win_updates: Enable unattended Windows Updates
      when get_version_output.changed
