---
- name: This sets up an httpd webserver
  hosts: tag_Name_Demo
  gather_facts: no
  sudo: yes
  tasks:
  - name: Install apache packages 
    yum:
      name: httpd
      state: latest
      use_backend: yum
   - name: Install apache packages 
    yum:
      name: wget
  - name: ensure httpd is running
    service:
      name: httpd 
      state: started
