---
- hosts: '{{ host_name }}'

  tasks:
    - name: Create mountable dir
      file: path=/nfs state=directory mode=777 owner=root group=root
    - name: set mountpoints
      mount: name=/nfs src=10.252.0.70:/testansible fstype=nfs state=mounted
