---
- hosts: localhost
  name: Volume Action
  tasks:
  - name: Volume Create
    na_ontap_volume:
      state: present
      name: testansible
      vserver: mgmt
      aggregate_name: aggr1_a700_01
      size: 10
      size_unit: gb
      policy: default
      junction_path: /testansible
      hostname: 10.251.0.22
      username: admin
      password: netapp1234
      https: true
      validate_certs: false
