---
- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
  # get date
  - set_fact: creationdate="{{lookup('pipe','date "+%Y/%m/%d %H:%M"')}}"
  # Create a VM from a template
  - name: create the VM
  vmware_guest:
      validate_certs: no
      datacenter: 'siriussdx'
      folder: ansible
      name: '{{ vm_name }}'
      state: poweredon
      guest_id: centos7_64Guest
      disk:
      - size_gb: 60
        type: thin
        datastore: mgmt_ds_01
      networks:
      - name: LAG-VLAN251
        ip: '{{ ip_address }}'
        netmask: 255.255.255.0
        gateway: 10.251.0.1
        dns_servers:
        - 10.250.0.100
        - 10.250.0.101
      hardware:
        memory_mb: 4096
        num_cpus: 2
      customization:
        dns_servers:
        - 10.250.0.100
        - 10.250.0.101
        domain : mgmt.siriussdx.com
        hostname: '{{ vm_name }}'
      template: centos_template
