---
- hosts: localhost
  gather_facts: false
  connection: local
  vars_prompt:
    - name: "vsphere_password"
      prompt: "vSphere Password"
    - name: "notes"
      prompt: "VM notes"
      private: no
      default: "Deployed with ansible"
    - name: "ip_address"
      prompt: "IP Address on 251 VLAN"
      private: no
  tasks:
  # get date
  - set_fact: creationdate="{{lookup('pipe','date "+%Y/%m/%d %H:%M"')}}"
  # Create a VM from a template
  - name: create the VM
    vmware_guest:
      hostname: mgmt-vcenter.mgmt.siriussdx.com
      username: administrator@vsphere.local
      password: '{{ vsphere_password }}'
      validate_certs: no
      datacenter: 'siriussdx'
      folder: ansible
      name: '{{ notes }}'
      state: poweredon
      guest_id: centos7_64Guest
      annotation: "{{ notes }} - {{ creationdate }}"
      disk:
      - size_gb: 60
        type: thin
        datastore: mgmt_ds_01
      networks:
      - name: LAG-VLAN251
        ip: '{{ ip_address }}'
        netmask: 255.255.255.0
        gateway: 10.251.0.1
        dns_servers:
        - 10.250.0.100
        - 10.250.0.101
      hardware:
        memory_mb: 4096
        num_cpus: 2
      customization:
        dns_servers:
        - 10.250.0.100
        - 10.250.0.101
        domain : mgmt.siriussdx.com
        hostname: test-test
      template: centos_template
      wait_for_ip_address: yes
    run_once: true
